name: CompatNoCheatPlus
main: me.asofold.bpl.cncp.CompatNoCheatPlus
version: ${project.version}-b${BUILD_NUMBER}
loadbefore:
- NoCheatPlus
softdepend:
- mcMMO
- Citizens
dev-url: http://dev.bukkit.org/server-mods/compatnocheatplus-cncp/
